### PR TITLE
test PR

### PR DESCRIPTION
**Pull request by epruesse**
* [ ] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ ] This PR adds a new recipe.
* [ ] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ ] This PR updates an existing recipe.
* [ ] This PR does something else (explain below).

### CODE REVIEW

**Comment by epruesse** [comment]
@biocondabot hello

**Comment by epruesse** [comment]
@bioconda-bot hello

**Comment by epruesse** [comment]
@bioconda-bot bump build number

**Comment by epruesse** [comment]
@biocondabot bump

**Comment by epruesse** [comment]
@BiocondaBot hello

**Comment by daler** [comment]
@BiocondaBot bump

**Comment by epruesse** [comment]
@BiocondaBot bump

**Comment by epruesse** [comment]
@BiocondaBot bump

**Comment by epruesse** [comment]
@BiocondaBot hello

**Comment by epruesse** [comment]
@BiocondaBot lint

**Comment by epruesse** [comment]
@BiocondaBot lint

**Comment by epruesse** [comment]
@BiocondaBot lint

**Comment by epruesse** [comment]
@BiocondaBot lint

**Comment by epruesse** [comment]
@biocondabot bump

**Comment by epruesse** [comment]
@BiocondaBot bump

**Comment by epruesse** [comment]
@biocondabot lint

**Comment by epruesse** [comment]
@biocondabot hello

**Comment by epruesse** [comment]
@biocondabot lint

**Comment by epruesse** [comment]
@bioconda-bot lint
@bioconda-bot lint
@bioconda-bot lint
@bioconda-bot lint
@bioconda-bot hello
@bioconda-bot bump

**Comment by epruesse** [comment]
@BiocondaBot bump

**Comment by epruesse** [comment]
@BiocondaBot hello

**Comment by epruesse** [comment]
@biocondabot bump

**Comment by epruesse** [comment]
@biocondabot lint

**Comment by epruesse** [comment]
@biocondabot bump

**Comment by epruesse** [comment]
@BiocondaBot bump

**Comment by epruesse** [comment]
@BiocondaBot lint

**Comment by epruesse** [comment]
@BiocondaBot lint

**Comment by epruesse** [comment]
@biocondabot bump

**Comment by epruesse** [comment]
@BiocondaBot lint

**Pull request closed without merging**
